language: ruby
rvm:
  - 2.5.1
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database mapped_test;' -U postgres
  - wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis
  - export PATH="/home/travis:$PATH"
  - export MAPPED_TOTP_ENCRYPTION_KEY="ICjFctlM7/tSD7LTrOWYGpocFSDvYNrtEhDS6ECOx20tlOGxT7ZIWovIHvfTaT/IISdNvg+BeyXP5oAXcpkueQ=="
#script: bundle exec rake test:system test # for unknown reasons system tests are failing on travis
script: bundle exec rake test
addons:
  apt:
    packages:
      - graphviz
  postgresql: "9.6"
  chrome: stable
