defaults: &defaults
  ttl: 1800
  readonly: false
  urlencode: false
  c_threshold: 10000
  compression: true
  debug: false
  namespace: ""
  sessions: true
  fragments: true
  memory: 128
  raise_errors: true
  fast_hash: false
  fastest_hash: false

development:
  <<: *defaults
  benchmarking: true
  servers:
    - <%= ENV['MEMCACHED_HOST'] || "127.0.0.1" %>:<%= ENV["MEMCACHED_PORT"] || 11211 %>

staging:
  <<: *defaults
  benchmarking: true
  servers:
    - <%= ENV['MEMCACHED_HOST'] || "127.0.0.1" %>:<%= ENV["MEMCACHED_PORT"] || 11211 %>

production:
  <<: *defaults
  benchmarking: true
  servers:
    - <%= ENV['MEMCACHED_HOST'] || "127.0.0.1" %>:<%= ENV["MEMCACHED_PORT"] || 11211 %>

test:
  <<: *defaults
  benchmarking: true
  servers:
    - <%= ENV['MEMCACHED_HOST'] || "127.0.0.1" %>:<%= ENV["MEMCACHED_PORT"] || 11211 %>
